export enum SMALL_TIME_UNIT {
  MINUTE = 'MINUTE',
  HOUR = 'HOUR',
}

export enum BIG_TIME_UNIT {
  DAY = 'DAY',
  WEEK = 'WEEK',
  MONTH = 'MONTH',
  YEAR = 'YEAR',
}

export enum TIME_UNIT {
  MINUTE = 'MINUTE',
  HOUR = 'HOUR',
  DAY = 'DAY',
  WEEK = 'WEEK',
  MONTH = 'MONTH',
  YEAR = 'YEAR',
}

export enum COMPENSATION_TIME_UNIT {
  HOUR = 'HOUR',
  DAY = 'DAY',
  WEEK = 'WEEK',
  MONTH = 'MONTH',
  YEAR = 'YEAR',
}

export enum WEEKDAY {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY',
}

export enum JOB_STATUS_TYPE {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum JOB_WORKPLACE_TYPE {
  REMOTE = 'REMOTE',
  ONSITE = 'ONSITE',
  HYBRID = 'HYBRID',
  OTHER = 'OTHER',
}

export enum JOB_EXPERIENCE_TYPE {
  REQUIRED = 'REQUIRED',
  PREFERRED = 'PREFERRED',
  NONE = 'NONE',
  YOUNG_SPECIALISTS = 'YOUNG_SPECIALISTS',
}

export enum JOB_EDUCATION_TYPE {
  NONE = 'NONE',
  SECONDARY = 'SECONDARY',
  PROFESSIONAL = 'PROFESSIONAL',
  HIGH_SCHOOL = 'HIGH_SCHOOL',
  COLLEGE = 'COLLEGE',
  LICENSE = 'LICENSE',
  MASTER = 'MASTER',
  DOCTORAL = 'DOCTORAL',
  OTHER = 'OTHER',
}

export enum USER_STATUS {
  JUST_REGISTERED = 'JUST_REGISTERED',
  CHOOSED_USER_TYPE = 'CHOOSED_USER_TYPE',
  REGISTERED = 'REGISTERED',
}

export enum USER_TYPE {
  EMPLOYEE = 'EMPLOYEE',
  EMPLOYER = 'EMPLOYER',
  ADMIN = 'ADMIN',
}
